overrides:
  - files: "*.js"
    options:
      tabWidth: 2
      arrowParens: "avoid"
      semi: true
      trailingComma: "none"
      printWidth: "120"
  - files: "*.json"
    options:
      semi: true
      tabWidth: 4
      useTabs: true
