// Code generated by awsEndpointGenerator; DO NOT EDIT.

package awsSupportedEndpoints

// Service constants

const COMPUTE_OPTIMIZERServiceID = "compute-optimizer"

const BATCHServiceID = "batch"

const TRANSCRIBESTREAMINGServiceID = "transcribestreaming"

const DYNAMODBServiceID = "dynamodb"

const GLOBALACCELERATORServiceID = "globalaccelerator"

const API_SAGEMAKERServiceID = "api.sagemaker"

const SIGNERServiceID = "signer"

const BACKUPServiceID = "backup"

const IOTEVENTSServiceID = "iotevents"

const ORGANIZATIONSServiceID = "organizations"

const FRAUDDETECTORServiceID = "frauddetector"

const BILLINGCONDUCTORServiceID = "billingconductor"

const IOTTWINMAKERServiceID = "iottwinmaker"

const IMPORTEXPORTServiceID = "importexport"

const PIServiceID = "pi"

const AIRFLOWServiceID = "airflow"

const MEDIACONNECTServiceID = "mediaconnect"

const TAGGINGServiceID = "tagging"

const APPSTREAM2ServiceID = "appstream2"

const SNOWBALLServiceID = "snowball"

const MODELS_LEXServiceID = "models.lex"

const DATA_JOBS_IOTServiceID = "data.jobs.iot"

const XRAYServiceID = "xray"

const LOOKOUTVISIONServiceID = "lookoutvision"

const DATA_MEDIASTOREServiceID = "data.mediastore"

const CONNECT_CAMPAIGNSServiceID = "connect-campaigns"

const IVSREALTIMEServiceID = "ivsrealtime"

const ELASTICACHEServiceID = "elasticache"

const LICENSE_MANAGER_USER_SUBSCRIPTIONSServiceID = "license-manager-user-subscriptions"

const APPMESHServiceID = "appmesh"

const CEServiceID = "ce"

const ELASTICFILESYSTEMServiceID = "elasticfilesystem"

const S3_OUTPOSTSServiceID = "s3-outposts"

const SECURITYLAKEServiceID = "securitylake"

const MACHINELEARNINGServiceID = "machinelearning"

const KENDRA_RANKINGServiceID = "kendra-ranking"

const CODECATALYSTServiceID = "codecatalyst"

const EKSServiceID = "eks"

const AMPLIFYBACKENDServiceID = "amplifybackend"

const METERING_MARKETPLACEServiceID = "metering.marketplace"

const ATHENAServiceID = "athena"

const GREENGRASSServiceID = "greengrass"

const SUPPORTAPPServiceID = "supportapp"

const SSM_CONTACTSServiceID = "ssm-contacts"

const WORKDOCSServiceID = "workdocs"

const FINSPACE_APIServiceID = "finspace-api"

const LAKEFORMATIONServiceID = "lakeformation"

const PIPESServiceID = "pipes"

const ENTITLEMENT_MARKETPLACEServiceID = "entitlement.marketplace"

const APPFLOWServiceID = "appflow"

const AMPLIFYServiceID = "amplify"

const LOOKOUTEQUIPMENTServiceID = "lookoutequipment"

const HEALTHServiceID = "health"

const WISDOMServiceID = "wisdom"

const COMPREHENDMEDICALServiceID = "comprehendmedical"

const DSServiceID = "ds"

const SESSION_QLDBServiceID = "session.qldb"

const RDS_DATAServiceID = "rds-data"

const CHIMEServiceID = "chime"

const EKS_AUTHServiceID = "eks-auth"

const MIGRATIONHUB_STRATEGYServiceID = "migrationhub-strategy"

const OIDCServiceID = "oidc"

const ACM_PCAServiceID = "acm-pca"

const IDENTITY_CHIMEServiceID = "identity-chime"

const ROUTE53RESOLVERServiceID = "route53resolver"

const CODESTAR_NOTIFICATIONSServiceID = "codestar-notifications"

const EDGE_SAGEMAKERServiceID = "edge.sagemaker"

const TRUSTEDADVISORServiceID = "trustedadvisor"

const ELASTICMAPREDUCEServiceID = "elasticmapreduce"

const IOTFLEETWISEServiceID = "iotfleetwise"

const ELASTICLOADBALANCINGServiceID = "elasticloadbalancing"

const MEMORY_DBServiceID = "memory-db"

const API_FLEETHUB_IOTServiceID = "api.fleethub.iot"

const DEVICEFARMServiceID = "devicefarm"

const MEDIASTOREServiceID = "mediastore"

const QLDBServiceID = "qldb"

const INSPECTORServiceID = "inspector"

const OMICSServiceID = "omics"

const ACCOUNTServiceID = "account"

const RUMServiceID = "rum"

const AOSSServiceID = "aoss"

const SERVICECATALOGServiceID = "servicecatalog"

const API_TUNNELING_IOTServiceID = "api.tunneling.iot"

const GRAFANAServiceID = "grafana"

const KAFKAServiceID = "kafka"

const MEDIAPACKAGEServiceID = "mediapackage"

const IDENTITYSTOREServiceID = "identitystore"

const EC2ServiceID = "ec2"

const RBINServiceID = "rbin"

const APPLICATION_AUTOSCALINGServiceID = "application-autoscaling"

const VERIFIEDPERMISSIONSServiceID = "verifiedpermissions"

const NEPTUNEServiceID = "neptune"

const EVIDENTLYServiceID = "evidently"

const DATAEXCHANGEServiceID = "dataexchange"

const DATASYNCServiceID = "datasync"

const ROBOMAKERServiceID = "robomaker"

const DAXServiceID = "dax"

const LOOKOUTMETRICSServiceID = "lookoutmetrics"

const FIREHOSEServiceID = "firehose"

const APSServiceID = "aps"

const FORECASTQUERYServiceID = "forecastquery"

const IVSCHATServiceID = "ivschat"

const INSPECTOR2ServiceID = "inspector2"

const RESILIENCEHUBServiceID = "resiliencehub"

const OPSWORKSServiceID = "opsworks"

const CODEBUILDServiceID = "codebuild"

const INGEST_TIMESTREAMServiceID = "ingest.timestream"

const SSOServiceID = "sso"

const LOGSServiceID = "logs"

const COMPREHENDServiceID = "comprehend"

const PROTONServiceID = "proton"

const AUTOSCALINGServiceID = "autoscaling"

const APIGATEWAYServiceID = "apigateway"

const EVENTSServiceID = "events"

const MEDIALIVEServiceID = "medialive"

const RESOURCE_EXPLORER_2ServiceID = "resource-explorer-2"

const MANAGEDBLOCKCHAINServiceID = "managedblockchain"

const CATALOG_MARKETPLACEServiceID = "catalog.marketplace"

const MEDIACONVERTServiceID = "mediaconvert"

const SYNTHETICSServiceID = "synthetics"

const ECSServiceID = "ecs"

const ROUTE53_RECOVERY_CONTROL_CONFIGServiceID = "route53-recovery-control-config"

const CODEARTIFACTServiceID = "codeartifact"

const MESSAGING_CHIMEServiceID = "messaging-chime"

const AUDITMANAGERServiceID = "auditmanager"

const APPRUNNERServiceID = "apprunner"

const CASESServiceID = "cases"

const MEDIAPACKAGE_VODServiceID = "mediapackage-vod"

const DATAPIPELINEServiceID = "datapipeline"

const SSM_SAPServiceID = "ssm-sap"

const BUDGETSServiceID = "budgets"

const KMSServiceID = "kms"

const QUICKSIGHTServiceID = "quicksight"

const IAMServiceID = "iam"

const NOTIFICATIONS_CONTACTSServiceID = "notifications-contacts"

const SECRETSMANAGERServiceID = "secretsmanager"

const GROUNDSTATIONServiceID = "groundstation"

const KAFKACONNECTServiceID = "kafkaconnect"

const CODEGURU_REVIEWERServiceID = "codeguru-reviewer"

const CLOUDTRAILServiceID = "cloudtrail"

const ARC_ZONAL_SHIFTServiceID = "arc-zonal-shift"

const AUTOSCALING_PLANSServiceID = "autoscaling-plans"

const DATABREWServiceID = "databrew"

const IOTANALYTICSServiceID = "iotanalytics"

const THINCLIENTServiceID = "thinclient"

const API_DETECTIVEServiceID = "api.detective"

const KINESISServiceID = "kinesis"

const CONTROLTOWERServiceID = "controltower"

const SERVICEQUOTASServiceID = "servicequotas"

const API_ELASTIC_INFERENCEServiceID = "api.elastic-inference"

const BEDROCKServiceID = "bedrock"

const NETWORKMANAGERServiceID = "networkmanager"

const SSM_INCIDENTSServiceID = "ssm-incidents"

const SAVINGSPLANSServiceID = "savingsplans"

const PERSONALIZEServiceID = "personalize"

const REDSHIFT_SERVERLESSServiceID = "redshift-serverless"

const EMR_SERVERLESSServiceID = "emr-serverless"

const FSXServiceID = "fsx"

const FORECASTServiceID = "forecast"

const RESOURCE_GROUPSServiceID = "resource-groups"

const APPSYNCServiceID = "appsync"

const TNBServiceID = "tnb"

const PARTICIPANT_CONNECTServiceID = "participant.connect"

const CLOUDFRONTServiceID = "cloudfront"

const API_ECR_PUBLICServiceID = "api.ecr-public"

const STREAMS_DYNAMODBServiceID = "streams.dynamodb"

const STORAGEGATEWAYServiceID = "storagegateway"

const KENDRAServiceID = "kendra"

const BRAKETServiceID = "braket"

const API_IOTWIRELESSServiceID = "api.iotwireless"

const MGHServiceID = "mgh"

const CLOUDHSMServiceID = "cloudhsm"

const IOTSECUREDTUNNELINGServiceID = "iotsecuredtunneling"

const TRANSLATEServiceID = "translate"

const RAMServiceID = "ram"

const API_MEDIATAILORServiceID = "api.mediatailor"

const NOTIFICATIONSServiceID = "notifications"

const HEALTHLAKEServiceID = "healthlake"

const CLOUDHSMV2ServiceID = "cloudhsmv2"

const QBUSINESSServiceID = "qbusiness"

const MTURK_REQUESTERServiceID = "mturk-requester"

const APPCONFIGDATAServiceID = "appconfigdata"

const MQServiceID = "mq"

const KINESISANALYTICSServiceID = "kinesisanalytics"

const GEOServiceID = "geo"

const APPTESTServiceID = "apptest"

const COGNITO_SYNCServiceID = "cognito-sync"

const GAMELIFTServiceID = "gamelift"

const GLUEServiceID = "glue"

const ACCESS_ANALYZERServiceID = "access-analyzer"

const IOTWIRELESSServiceID = "iotwireless"

const MEETINGS_CHIMEServiceID = "meetings-chime"

const DATA_ATS_IOTServiceID = "data-ats.iot"

const APP_INTEGRATIONSServiceID = "app-integrations"

const WORKMAILServiceID = "workmail"

const IOTTHINGSGRAPHServiceID = "iotthingsgraph"

const SAGEMAKER_GEOSPATIALServiceID = "sagemaker-geospatial"

const WELLARCHITECTEDServiceID = "wellarchitected"

const SWFServiceID = "swf"

const RUNTIME_LEXServiceID = "runtime.lex"

const DEVOPS_GURUServiceID = "devops-guru"

const COST_OPTIMIZATION_HUBServiceID = "cost-optimization-hub"

const CLOUDFORMATIONServiceID = "cloudformation"

const METRICS_SAGEMAKERServiceID = "metrics.sagemaker"

const DLMServiceID = "dlm"

const DATAZONEServiceID = "datazone"

const CONFIGServiceID = "config"

const STSServiceID = "sts"

const REDSHIFTServiceID = "redshift"

const ELASTICTRANSCODERServiceID = "elastictranscoder"

const LAMBDAServiceID = "lambda"

const CONTACT_LENSServiceID = "contact-lens"

const WAF_REGIONALServiceID = "waf-regional"

const ESServiceID = "es"

const CONNECTServiceID = "connect"

const SNSServiceID = "sns"

const ACMServiceID = "acm"

const INTERNETMONITORServiceID = "internetmonitor"

const SECURITYHUBServiceID = "securityhub"

const CLOUDCONTROLAPIServiceID = "cloudcontrolapi"

const MEDIA_PIPELINES_CHIMEServiceID = "media-pipelines-chime"

const PRIVATE_NETWORKSServiceID = "private-networks"

const REKOGNITIONServiceID = "rekognition"

const VOICE_CHIMEServiceID = "voice-chime"

const OUTPOSTSServiceID = "outposts"

const STATESServiceID = "states"

const COGNITO_IDPServiceID = "cognito-idp"

const CURServiceID = "cur"

const DIRECTCONNECTServiceID = "directconnect"

const MONITORINGServiceID = "monitoring"

const SCHEDULERServiceID = "scheduler"

const EMR_CONTAINERSServiceID = "emr-containers"

const OPSWORKS_CMServiceID = "opsworks-cm"

const CODECOMMITServiceID = "codecommit"

const TAXServiceID = "tax"

const PORTAL_SSOServiceID = "portal.sso"

const EMAILServiceID = "email"

const RDSServiceID = "rds"

const TRANSFERServiceID = "transfer"

const BACKUP_GATEWAYServiceID = "backup-gateway"

const IVSServiceID = "ivs"

const MARKETPLACECOMMERCEANALYTICSServiceID = "marketplacecommerceanalytics"

const MODELS_V2_LEXServiceID = "models-v2-lex"

const SSM_QUICKSETUPServiceID = "ssm-quicksetup"

const SDBServiceID = "sdb"

const MGNServiceID = "mgn"

const IOTServiceID = "iot"

const VOICEIDServiceID = "voiceid"

const IOTEVENTSDATAServiceID = "ioteventsdata"

const IOTSITEWISEServiceID = "iotsitewise"

const SHIELDServiceID = "shield"

const TEXTRACTServiceID = "textract"

const APPLICATIONINSIGHTSServiceID = "applicationinsights"

const DRSServiceID = "drs"

const M2ServiceID = "m2"

const MANAGEDBLOCKCHAIN_QUERYServiceID = "managedblockchain-query"

const SERVICECATALOG_APPREGISTRYServiceID = "servicecatalog-appregistry"

const CODESTAR_CONNECTIONSServiceID = "codestar-connections"

const CLOUD9ServiceID = "cloud9"

const LICENSE_MANAGERServiceID = "license-manager"

const SQSServiceID = "sqs"

const OSISServiceID = "osis"

const POLLYServiceID = "polly"

const EBSServiceID = "ebs"

const ROUTE53DOMAINSServiceID = "route53domains"

const SMSServiceID = "sms"

const CASSANDRAServiceID = "cassandra"

const APPCONFIGServiceID = "appconfig"

const SERVERLESSREPOServiceID = "serverlessrepo"

const GLACIERServiceID = "glacier"

const TRANSCRIBEServiceID = "transcribe"

const DOCDBServiceID = "docdb"

const VPC_LATTICEServiceID = "vpc-lattice"

const CLOUDSEARCHServiceID = "cloudsearch"

const SMS_VOICEServiceID = "sms-voice"

const OAMServiceID = "oam"

const API_IOTDEVICEADVISORServiceID = "api.iotdeviceadvisor"

const WAFV2ServiceID = "wafv2"

const SSMServiceID = "ssm"

const RUNTIME_V2_LEXServiceID = "runtime-v2-lex"

const KINESISVIDEOServiceID = "kinesisvideo"

const DMSServiceID = "dms"

const CODEDEPLOYServiceID = "codedeploy"

const LIGHTSAILServiceID = "lightsail"

const SERVICEDISCOVERYServiceID = "servicediscovery"

const SUPPORTServiceID = "support"

const DISCOVERYServiceID = "discovery"

const PROFILEServiceID = "profile"

const LICENSE_MANAGER_LINUX_SUBSCRIPTIONSServiceID = "license-manager-linux-subscriptions"

const ROUTE53ServiceID = "route53"

const API_ECRServiceID = "api.ecr"

const COGNITO_IDENTITYServiceID = "cognito-identity"

const API_PRICINGServiceID = "api.pricing"

const SCHEMASServiceID = "schemas"

const ELASTICBEANSTALKServiceID = "elasticbeanstalk"

const CLOUDTRAIL_DATAServiceID = "cloudtrail-data"

const MIGRATIONHUB_ORCHESTRATORServiceID = "migrationhub-orchestrator"

const WORKSPACES_WEBServiceID = "workspaces-web"

const SIMSPACEWEAVERServiceID = "simspaceweaver"

const WAFServiceID = "waf"

const AGREEMENT_MARKETPLACEServiceID = "agreement-marketplace"

const PINPOINTServiceID = "pinpoint"

const MOBILEANALYTICSServiceID = "mobileanalytics"

const GUARDDUTYServiceID = "guardduty"

const AMPLIFYUIBUILDERServiceID = "amplifyuibuilder"

const FMSServiceID = "fms"

const MEDIAPACKAGEV2ServiceID = "mediapackagev2"

const WORKSPACESServiceID = "workspaces"

const S3ServiceID = "s3"

const MACIE2ServiceID = "macie2"

const DATA_IOTServiceID = "data.iot"

const FINSPACEServiceID = "finspace"

const RUNTIME_SAGEMAKERServiceID = "runtime.sagemaker"

const CLOUDDIRECTORYServiceID = "clouddirectory"

const CODEPIPELINEServiceID = "codepipeline"

const S3_CONTROLServiceID = "s3-control"

const CLEANROOMSServiceID = "cleanrooms"

const NETWORK_FIREWALLServiceID = "network-firewall"

const ROLESANYWHEREServiceID = "rolesanywhere"

