package aws

import (
	"context"
	"fmt"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/guardduty"

	guarddutyEndpoint "github.com/turbot/steampipe-plugin-aws/awsSupportedEndpoints"

	"github.com/turbot/steampipe-plugin-sdk/v5/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin/transform"
)

//// TABLE DEFINITION

type threatIntelSetInfo = struct {
	guardduty.GetThreatIntelSetOutput
	ThreatIntelSetID string
	DetectorID       string
}

func tableAwsGuardDutyThreatIntelSet(_ context.Context) *plugin.Table {
	return &plugin.Table{
		Name:        "aws_guardduty_threat_intel_set",
		Description: "AWS GuardDuty ThreatIntelSet",
		Get: &plugin.GetConfig{
			KeyColumns: plugin.AllColumns([]string{"detector_id", "threat_intel_set_id"}),
			IgnoreConfig: &plugin.IgnoreConfig{
				ShouldIgnoreErrorFunc: shouldIgnoreErrors([]string{"InvalidInputException", "BadRequestException"}),
			},
			Hydrate: getGuardDutyThreatIntelSet,
			Tags:    map[string]string{"service": "guardduty", "action": "GetThreatIntelSet"},
		},
		List: &plugin.ListConfig{
			ParentHydrate: listGuardDutyDetectors,
			Hydrate:       listGuardDutyThreatIntelSets,
			Tags:          map[string]string{"service": "guardduty", "action": "ListThreatIntelSets"},
			KeyColumns: []*plugin.KeyColumn{
				{Name: "detector_id", Require: plugin.Optional},
			},
		},
		HydrateConfig: []plugin.HydrateConfig{
			{
				Func: getGuardDutyThreatIntelSet,
				Tags: map[string]string{"service": "guardduty", "action": "GetThreatIntelSet"},
			},
		},
		GetMatrixItemFunc: SupportedRegionMatrix(guarddutyEndpoint.GUARDDUTYServiceID),
		Columns: awsRegionalColumns([]*plugin.Column{
			{
				Name:        "name",
				Description: "A ThreatIntelSet name displayed in all findings that are generated by activity that involves IP addresses included in this ThreatIntelSet.",
				Type:        proto.ColumnType_STRING,
				Hydrate:     getGuardDutyThreatIntelSet,
			},
			{
				Name:        "threat_intel_set_id",
				Description: "The ID of the ThreatIntelSet.",
				Type:        proto.ColumnType_STRING,
				Transform:   transform.FromField("ThreatIntelSetID"),
			},
			{
				Name:        "detector_id",
				Description: "The ID of the detector.",
				Type:        proto.ColumnType_STRING,
				Hydrate:     getGuardDutyThreatIntelSet,
				Transform:   transform.FromField("DetectorID"),
			},
			{
				Name:        "format",
				Description: "The format of the threatIntelSet.",
				Type:        proto.ColumnType_STRING,
				Hydrate:     getGuardDutyThreatIntelSet,
			},
			{
				Name:        "location",
				Description: "The URI of the file that contains the ThreatIntelSet.",
				Type:        proto.ColumnType_STRING,
				Hydrate:     getGuardDutyThreatIntelSet,
			},
			{
				Name:        "status",
				Description: "The status of threatIntelSet file uploaded.",
				Type:        proto.ColumnType_STRING,
				Hydrate:     getGuardDutyThreatIntelSet,
			},
			// Standard columns
			{
				Name:        "title",
				Description: resourceInterfaceDescription("title"),
				Type:        proto.ColumnType_STRING,
				Hydrate:     getGuardDutyThreatIntelSet,
				Transform:   transform.FromField("Name"),
			},
			{
				Name:        "tags",
				Description: resourceInterfaceDescription("tags"),
				Type:        proto.ColumnType_JSON,
				Hydrate:     getGuardDutyThreatIntelSet,
			},
			{
				Name:        "akas",
				Description: resourceInterfaceDescription("akas"),
				Type:        proto.ColumnType_JSON,
				Hydrate:     getAwsGuardDutyThreatIntelSetAkas,
				Transform:   transform.FromValue(),
			},
		}),
	}
}

//// LIST FUNCTION

func listGuardDutyThreatIntelSets(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
	// Get details of detector
	detectorID := h.Item.(detectorInfo).DetectorID

	// Create session
	svc, err := GuardDutyClient(ctx, d)
	if err != nil {
		plugin.Logger(ctx).Error("aws_guardduty_threat_intel_set.getGuardDutyThreatIntelSet", "get_client_error", err)
		return nil, err
	}

	equalQuals := d.EqualsQuals

	// Minimize the API call with the given detector id
	if equalQuals["detector_id"] != nil {
		if equalQuals["detector_id"].GetStringValue() != detectorID {
			return nil, nil
		}
	}

	maxItems := int32(50)
	input := &guardduty.ListThreatIntelSetsInput{
		DetectorId: &detectorID,
	}

	// Reduce the basic request limit down if the user has only requested a small number of rows
	if d.QueryContext.Limit != nil {
		limit := int32(*d.QueryContext.Limit)
		if limit < maxItems {
			input.MaxResults = aws.Int32(limit)
		}
	}

	paginator := guardduty.NewListThreatIntelSetsPaginator(svc, input, func(o *guardduty.ListThreatIntelSetsPaginatorOptions) {
		o.Limit = maxItems
		o.StopOnDuplicateToken = true
	})

	for paginator.HasMorePages() {
		// apply rate limiting
		d.WaitForListRateLimit(ctx)

		output, err := paginator.NextPage(ctx)
		if err != nil {
			plugin.Logger(ctx).Error("aws_guardduty_ipset.getAwsGuardDutyIPSet", "api_error", err)
			return nil, err
		}

		for _, item := range output.ThreatIntelSetIds {
			d.StreamListItem(ctx, threatIntelSetInfo{
				ThreatIntelSetID: item,
				DetectorID:       detectorID,
			})

			// Context may get cancelled due to manual cancellation or if the limit has been reached
			if d.RowsRemaining(ctx) == 0 {
				return nil, nil
			}
		}
	}

	return nil, nil
}

//// HYDRATE FUNCTIONS

func getGuardDutyThreatIntelSet(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
	// Create Session
	svc, err := GuardDutyClient(ctx, d)
	if err != nil {
		plugin.Logger(ctx).Error("aws_guardduty_threat_intel_set.getGuardDutyThreatIntelSet", "get_client_error", err)
		return nil, err
	}

	var id, detectorID string

	if h.Item != nil {
		detectorID = h.Item.(threatIntelSetInfo).DetectorID
		id = h.Item.(threatIntelSetInfo).ThreatIntelSetID
	} else {
		detectorID = d.EqualsQuals["detector_id"].GetStringValue()
		id = d.EqualsQuals["threat_intel_set_id"].GetStringValue()
	}

	params := &guardduty.GetThreatIntelSetInput{
		DetectorId:       &detectorID,
		ThreatIntelSetId: &id,
	}

	op, err := svc.GetThreatIntelSet(ctx, params)
	if err != nil {
		plugin.Logger(ctx).Error("aws_guardduty_threat_intel_set.getGuardDutyThreatIntelSet", "api_error", err)
		return nil, err
	}

	return threatIntelSetInfo{*op, id, detectorID}, nil
}

//// TRANSFORM FUNCTIONS

func getAwsGuardDutyThreatIntelSetAkas(ctx context.Context, d *plugin.QueryData, h *plugin.HydrateData) (interface{}, error) {
	data := h.Item.(threatIntelSetInfo)
	region := d.EqualsQualString(matrixKeyRegion)

	c, err := getCommonColumns(ctx, d, h)
	if err != nil {
		plugin.Logger(ctx).Error("aws_guardduty_threat_intel_set.getAwsGuardDutyThreatIntelSetAkas", "api_error", err)
		return nil, err
	}
	commonColumnData := c.(*awsCommonColumnData)
	aka := fmt.Sprintf("arn:%s:guardduty:%s:%s:detector/%s/threatintelset/%s", commonColumnData.Partition, region, commonColumnData.AccountId, data.DetectorID, data.ThreatIntelSetID)

	return []string{aka}, nil
}
