#!/usr/bin/env python3

import os
import json
import requests
import subprocess
from jinja2 import Template
from encoders import CompactishJsonEncoder

# URL for fetching AWS endpoints JSON data
ENDPOINTS_JSON_URL = "https://raw.githubusercontent.com/aws/aws-sdk-go-v2/master/codegen/smithy-aws-go-codegen/src/main/resources/software/amazon/smithy/aws/go/codegen/endpoints.json"

# Define output directories
OUTPUT_DIR = "internal/aws_endpoint_generator"
ENDPOINTS_FILE_PATH = os.path.join(OUTPUT_DIR, "endpoints.json")
CUSTOM_ENDPOINTS_FILE_PATH = os.path.relpath(
    os.path.join(os.path.dirname(__file__), "custom_endpoints.json"),
    os.getcwd())
GENERATED_GO_FILE = "aws/endpoint_service_ids_gen.go"

# Ensure output directories exist
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(os.path.dirname(GENERATED_GO_FILE), exist_ok=True)


def download_file(url, output_path):
    """Downloads a file from the given URL and saves it locally."""
    try:
        response = requests.get(url, stream=True)
        response.raise_for_status()

        with open(output_path, "wb") as file:
            for chunk in response.iter_content(chunk_size=8192):
                file.write(chunk)

        print(f"File downloaded successfully: {output_path}")
    except requests.exceptions.RequestException as e:
        print(f"Error downloading file: {e}")
        exit(1)


def merge_custom_endpoints(endpoint_file_path, custom_endpoint_file_path):
    """Merge the downloaded AWS endpoints file with our custom set of endpoints.

    AWS Go SDK v2 has officially stated that the endpoint metadata file (which this package uses to
    resolve service region information) is intended as a purely internal construct and is not used
    as the default approach to endpoint resolution. This means that for some newer services, endpoint
    metadata may not be present.

    As such, this package now maintains its own set of endpoint metadata which is merged into the set
    pulled from AWS Go SDK v2.

    See also:
        - https://github.com/aws/aws-sdk-go-v2/issues/2740
        - https://github.com/aws/aws-sdk-go-v2/discussions/1026
    """
    try:
        with open(endpoint_file_path, "r", encoding="utf-8") as file:
            aws_endpoints = json.load(file)

        with open(custom_endpoint_file_path, "r", encoding="utf-8") as file:
            custom_endpoints = json.load(file)
    except Exception as e:
        print(f"Error parsing JSON: {e}")
        exit(1)

    for service, partition_endpoints in custom_endpoints.items():
        for partition in aws_endpoints["partitions"]:
            partition_name = partition["partition"]
            if partition_name not in partition_endpoints:
                continue

            aws_service_metadata = partition["services"].get(service, {"endpoints": {}})

            for region, region_endpoints in partition_endpoints[partition_name].items():
                # Validate the region against the partition.
                if region not in partition["regions"]:
                    print(f"Invalid region `{region}` for partition `{partition}`")
                    exit(1)

                if region not in aws_service_metadata["endpoints"]:
                    aws_service_metadata["endpoints"][region] = {"variants": []}

                aws_service_metadata["endpoints"][region]["variants"].extend([
                    {
                        "hostname": region_endpoint,
                        "tags": ["custom"]
                    }
                    for region_endpoint in region_endpoints
                ])

            partition["services"][service] = aws_service_metadata

    try:
        with open(endpoint_file_path, "w", encoding="utf-8") as file:
            # Use the customised encoder to minimise diffs.
            json.dump(aws_endpoints, file, cls=CompactishJsonEncoder, indent=2, separators=(',', ' : '))

        print(f"Merged custom endpoints from {custom_endpoint_file_path} into {endpoint_file_path}")
    except Exception as e:
        print(f"Error writing merged file: {e}")
        exit(1)


def extract_unique_service_keys(endpoint_file_path):
    """Extracts unique service keys from the downloaded JSON file."""
    try:
        with open(endpoint_file_path, "r", encoding="utf-8") as file:
            data = json.load(file)

        service_keys = sorted(set(
            key for partition in data.get("partitions", []) for key in partition.get("services", {}).keys()
        ))

        return service_keys
    except Exception as e:
        print(f"Error parsing JSON: {e}")
        exit(1)


def generate_go_file(service_keys, output_file):
    """Generates a Go file with service ID constants using a template."""
    template_str = """// Code generated by awsEndpointGenerator; DO NOT EDIT.

package aws

// Service constants
{% for service in service_keys %}
const AWS_{{ service | replace(".", "_") | replace("-", "_") | upper }}_SERVICE_ID = "{{ service }}"
{% endfor %}
"""

    template = Template(template_str)
    rendered_content = template.render(service_keys=service_keys)

    try:
        with open(output_file, "w", encoding="utf-8") as file:
            file.write(rendered_content)
        print(f"Go file generated: {output_file}")
    except Exception as e:
        print(f"Error writing Go file: {e}")
        exit(1)


def format_go_file(file_path):
    """Formats the generated Go file using gofmt."""
    try:
        subprocess.run(["go", "fmt", file_path], check=True)
        print(f"Formatted {file_path} using gofmt.")
    except subprocess.CalledProcessError as e:
        print(f"Error formatting Go file: {e}")
        exit(1)


def main():
    """Main execution flow."""
    print("Working Directory:", os.getcwd())

    # Step 1: Download the JSON file
    download_file(ENDPOINTS_JSON_URL, ENDPOINTS_FILE_PATH)

    # Step 2: Merge the downloaded JSON file with the custom set of endpoints that are maintained internally.
    merge_custom_endpoints(ENDPOINTS_FILE_PATH, CUSTOM_ENDPOINTS_FILE_PATH)

    # Step 3: Extract unique service keys
    service_keys = extract_unique_service_keys(ENDPOINTS_FILE_PATH)

    # Step 4: Generate the Go file
    generate_go_file(service_keys, GENERATED_GO_FILE)

    # Step 5: Format the generated Go file
    format_go_file(GENERATED_GO_FILE)


if __name__ == "__main__":
    main()
