 #!/bin/bash
 RED="\e[31m"
 GREEN="\e[32m"
 BLACK="\e[30m"
 BOLDGREEN="\e[1;${GREEN}"
 YELLOW="\e[93m"
 ENDCOLOR="\e[0m"

# Define your function here
run_test () {
   echo -e "${YELLOW}Running $1 ${ENDCOLOR}"
 if ! ./tint.js $1 >> output.txt
   then
    echo -e "${RED}Failed -> $1 ${ENDCOLOR}"
    echo $1 >> failed_tests.txt
  else
    echo -e "${BOLDGREEN}Passed -> $1 ${ENDCOLOR}"
    echo $1 >> passed_tests.txt
   fi
 }

 # output.txt - store output of each test
 # failed_tests.txt - names of failed test
 # passed_tests.txt names of passed test

 # removes files from previous test
rm -rf output.txt failed_tests.txt passed_tests.txt
date >> output.txt
date >> failed_tests.txt
date >> passed_tests.txt

runt_test aws_accessanalyzer_analyzer
runt_test aws_acm_certificate
runt_test aws_acmpca_certificate_authority
runt_test aws_amplify_app
runt_test aws_api_gateway_api_key
runt_test aws_api_gateway_authorizer
runt_test aws_api_gateway_method
runt_test aws_api_gateway_rest_api
runt_test aws_api_gateway_stage
runt_test aws_api_gateway_usage_plan
runt_test aws_api_gatewayv2_api
runt_test aws_api_gatewayv2_domain_name
runt_test aws_api_gatewayv2_integration
runt_test aws_api_gatewayv2_route
runt_test aws_api_gatewayv2_stage
runt_test aws_app_runner_service
runt_test aws_appautoscaling_policy
runt_test aws_appautoscaling_target
runt_test aws_appconfig_application
runt_test aws_appstream_fleet
runt_test aws_appsync_graphql_api
runt_test aws_auditmanager_assessment
runt_test aws_auditmanager_control
runt_test aws_auditmanager_framework
runt_test aws_backup_framework
runt_test aws_backup_plan
runt_test aws_backup_report_plan
runt_test aws_backup_selection
runt_test aws_backup_vault
runt_test aws_cloudformation_stack
runt_test aws_cloudformation_stack_resource
runt_test aws_cloudformation_stack_set
runt_test aws_cloudfront_cache_policy
runt_test aws_cloudfront_distribution
runt_test aws_cloudfront_function
runt_test aws_cloudfront_origin_access_identity
runt_test aws_cloudfront_origin_request_policy
runt_test aws_cloudfront_response_headers_policy
runt_test aws_cloudsearch_domain
runt_test aws_cloudtrail_event_data_store
runt_test aws_cloudtrail_trail
runt_test aws_cloudwatch_alarm
runt_test aws_cloudwatch_log_group
runt_test aws_cloudwatch_log_resource_policy
runt_test aws_cloudwatch_log_stream
runt_test aws_codeartifact_domain
runt_test aws_codeartifact_repository
runt_test aws_codebuild_project
runt_test aws_codebuild_source_credential
runt_test aws_codecommit_repository
runt_test aws_codedeploy_app
runt_test aws_codedeploy_deployment_config
runt_test aws_codedeploy_deployment_group
runt_test aws_codepipeline_pipeline
runt_test aws_config_aggregate_authorization
runt_test aws_config_configuration_recorder
runt_test aws_config_conformance_pack
runt_test aws_config_rule
runt_test aws_dax_cluster
runt_test aws_dax_parameter
runt_test aws_dax_parameter_group
runt_test aws_dax_subnet_group
runt_test aws_directory_service_directory
runt_test aws_dlm_lifecycle_policy
runt_test aws_dms_certificate
runt_test aws_dms_endpoint
runt_test aws_dms_replication_instance
runt_test aws_dms_replication_task
runt_test aws_docdb_cluster
runt_test aws_docdb_cluster_instance
runt_test aws_docdb_cluster_snapshot
runt_test aws_dynamodb_table
runt_test aws_ebs_snapshot
runt_test aws_ebs_volume
runt_test aws_ec2_ami
runt_test aws_ec2_ami_shared
runt_test aws_ec2_application_load_balancer
runt_test aws_ec2_autoscaling_group
runt_test aws_ec2_capacity_reservation
runt_test aws_ec2_classic_load_balancer
runt_test aws_ec2_gateway_load_balancer
runt_test aws_ec2_instance
runt_test aws_ec2_key_pair
runt_test aws_ec2_launch_configuration
runt_test aws_ec2_launch_template
runt_test aws_ec2_launch_template_version
runt_test aws_ec2_load_balancer_listener
runt_test aws_ec2_managed_prefix_list
runt_test aws_ec2_managed_prefix_list_entry
runt_test aws_ec2_network_interface
runt_test aws_ec2_network_load_balancer
runt_test aws_ec2_regional_settings
runt_test aws_ec2_ssl_policy
runt_test aws_ec2_target_group
runt_test aws_ec2_transit_gateway
runt_test aws_ec2_transit_gateway_route
runt_test aws_ec2_transit_gateway_route_table
runt_test aws_ec2_transit_gateway_vpc_attachment
runt_test aws_ecr_registry_scanning_configuration
runt_test aws_ecr_repository
runt_test aws_ecrpublic_repository
runt_test aws_ecs_cluster
runt_test aws_ecs_service
runt_test aws_ecs_task_definition
runt_test aws_efs_access_point
runt_test aws_efs_file_system
runt_test aws_efs_mount_target
runt_test aws_eks_addon
runt_test aws_eks_addon_version
runt_test aws_eks_cluster
runt_test aws_eks_fargate_profile
runt_test aws_eks_identity_provider_config
runt_test aws_elastic_beanstalk_application
runt_test aws_elastic_beanstalk_application_version
runt_test aws_elastic_beanstalk_environment
runt_test aws_elasticache_cluster
runt_test aws_elasticache_parameter_group
runt_test aws_elasticache_replication_group
runt_test aws_elasticache_subnet_group
runt_test aws_elasticsearch_domain
runt_test aws_emr_cluster
runt_test aws_emr_instance_fleet
runt_test aws_emr_instance_group
runt_test aws_emr_security_configuration
runt_test aws_eventbridge_bus
runt_test aws_eventbridge_rule
runt_test aws_fsx_file_system
runt_test aws_glacier_vault
runt_test aws_glue_catalog_database
runt_test aws_glue_catalog_table
runt_test aws_glue_connection
runt_test aws_glue_crawler
runt_test aws_glue_data_catalog_encryption_settings
runt_test aws_glue_dev_endpoint
runt_test aws_glue_job
runt_test aws_glue_security_configuration
runt_test aws_guardduty_detector
runt_test aws_guardduty_filter
runt_test aws_guardduty_finding
runt_test aws_guardduty_ipset
runt_test aws_guardduty_member
runt_test aws_guardduty_publishing_destination
runt_test aws_guardduty_threat_intel_set
runt_test aws_iam_access_advisor
runt_test aws_iam_access_key
runt_test aws_iam_account_password_policy
runt_test aws_iam_account_summary
runt_test aws_iam_group
runt_test aws_iam_open_id_connect_provider
runt_test aws_iam_policy
runt_test aws_iam_policy_simulator
runt_test aws_iam_role
runt_test aws_iam_saml_provider
runt_test aws_iam_server_certificate
runt_test aws_iam_service_specific_credential
runt_test aws_iam_user
runt_test aws_identitystore_group
runt_test aws_identitystore_user
runt_test aws_inspector_assessment_target
runt_test aws_inspector_assessment_template
runt_test aws_iot_thing
runt_test aws_iot_thing_group
runt_test aws_iot_thing_type
runt_test aws_keyspaces_table
runt_test aws_kinesis_consumer
runt_test aws_kinesis_firehose_delivery_stream
runt_test aws_kinesis_stream
runt_test aws_kinesis_video_stream
runt_test aws_kinesisanalyticsv2_application
runt_test aws_kms_alias
runt_test aws_kms_key
runt_test aws_lambda_alias
runt_test aws_lambda_function
runt_test aws_lambda_version
runt_test aws_lightsail_bucket
runt_test aws_lightsail_instance
runt_test aws_macie2_classification_job
runt_test aws_media_store_container
runt_test aws_memorydb_cluster
runt_test aws_mq_broker
runt_test aws_msk_serverless_cluster
runt_test aws_neptune_db_cluster
runt_test aws_neptune_db_cluster_snapshot
runt_test aws_networkfirewall_firewall
runt_test aws_networkfirewall_firewall_policy
runt_test aws_opensearch_domain
runt_test aws_organizations_account
runt_test aws_pinpoint_app
runt_test aws_ram_principal_association
runt_test aws_ram_resource_association
runt_test aws_rds_db_cluster
runt_test aws_rds_db_cluster_parameter_group
runt_test aws_rds_db_cluster_snapshot
runt_test aws_rds_db_event_subscription
runt_test aws_rds_db_instance
runt_test aws_rds_db_option_group
runt_test aws_rds_db_parameter_group
runt_test aws_rds_db_proxy
runt_test aws_rds_db_snapshot
runt_test aws_rds_db_subnet_group
runt_test aws_redshift_cluster
runt_test aws_redshift_event_subscription
runt_test aws_redshift_parameter_group
runt_test aws_redshift_snapshot
runt_test aws_redshift_subnet_group
runt_test aws_redshiftserverless_namespace
runt_test aws_redshiftserverless_workgroup
runt_test aws_region
runt_test aws_route53_health_check
runt_test aws_route53_query_log
runt_test aws_route53_record
runt_test aws_route53_resolver_endpoint
runt_test aws_route53_resolver_query_log_config
runt_test aws_route53_resolver_rule
runt_test aws_route53_traffic_policy
runt_test aws_route53_traffic_policy_instance
runt_test aws_route53_vpc_association_authorization
runt_test aws_route53_zone
runt_test aws_s3_access_point
runt_test aws_s3_bucket
runt_test aws_sagemaker_app
runt_test aws_sagemaker_domain
runt_test aws_sagemaker_endpoint_configuration
runt_test aws_sagemaker_model
runt_test aws_sagemaker_notebook_instance
runt_test aws_secretsmanager_secret
runt_test aws_securityhub_action_target
runt_test aws_securityhub_hub
runt_test aws_securityhub_insight
runt_test aws_securityhub_member
runt_test aws_securityhub_product
runt_test aws_securityhub_standards_control
runt_test aws_securityhub_standards_subscription
runt_test aws_serverlessapplicationrepository_application
runt_test aws_service_discovery_instance
runt_test aws_service_discovery_namespace
runt_test aws_service_discovery_service
runt_test aws_servicecatalog_portfolio
runt_test aws_servicecatalog_product
runt_test aws_servicequotas_default_service_quota
runt_test aws_servicequotas_service_quota
runt_test aws_ses_email_identity
runt_test aws_sfn_state_machine
runt_test aws_sfn_state_machine_execution
runt_test aws_sfn_state_machine_execution_history
runt_test aws_sns_subscription
runt_test aws_sns_topic
runt_test aws_sns_topic_subscription
runt_test aws_sqs_queue
runt_test aws_ssm_association
runt_test aws_ssm_document
runt_test aws_ssm_maintenance_window
runt_test aws_ssm_managed_instance
runt_test aws_ssm_managed_instance_compliance
runt_test aws_ssm_parameter
runt_test aws_ssm_patch_baseline
runt_test aws_ssoadmin_account_assignment
runt_test aws_ssoadmin_instance
runt_test aws_ssoadmin_managed_policy_attachment
runt_test aws_ssoadmin_permission_set
runt_test aws_tagging_resource
runt_test aws_timestreamwrite_database
runt_test aws_timestreamwrite_table
runt_test aws_transfer_server
runt_test aws_transfer_user
runt_test aws_vpc
runt_test aws_vpc_customer_gateway
runt_test aws_vpc_dhcp_options
runt_test aws_vpc_egress_only_internet_gateway
runt_test aws_vpc_eip
runt_test aws_vpc_endpoint
runt_test aws_vpc_endpoint_service
runt_test aws_vpc_flow_log
runt_test aws_vpc_internet_gateway
runt_test aws_vpc_nat_gateway
runt_test aws_vpc_network_acl
runt_test aws_vpc_peering_connection
runt_test aws_vpc_route
runt_test aws_vpc_route_table
runt_test aws_vpc_security_group
runt_test aws_vpc_subnet
runt_test aws_vpc_vpn_connection
runt_test aws_vpc_vpn_gateway
runt_test aws_waf_rate_based_rule
runt_test aws_waf_rule
runt_test aws_waf_rule_group
runt_test aws_waf_web_acl
runt_test aws_wafregional_rule
runt_test aws_wafregional_rule_group
runt_test aws_wafregional_web_acl
runt_test aws_wafv2_ip_set
runt_test aws_wafv2_regex_pattern_set
runt_test aws_wafv2_rule_group
runt_test aws_wafv2_web_acl
runt_test aws_wellarchitected_workload

date >> output.txt
date >> failed_tests.txt
date >> passed_tests.txt