name: "Stale Issues and PRs"
on:
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:
    inputs:
      debugOnly:
        description: "Set to true for a dry run"
        required: false
        default: "false"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Stale issues and PRs
        id: stale-issues-and-prs
        uses: actions/stale@v5
        with:
          close-issue-message: |
            'This issue was closed because it has been stalled for 60 days with no activity.'
          close-issue-reason: 'not_planned'
          close-pr-message: |
            'This PR was closed because it has been stalled for 60 days with no activity.'
          # Set days-before-close to 30 because we want to close the issue/PR after 60 days total, since days-before-stale is set to 30
          days-before-close: 30
          days-before-stale: 30
          debug-only: ${{ github.event.inputs.debugOnly }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: 'stale'
          stale-issue-message: |
            'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
          stale-pr-label: 'stale'
          stale-pr-message: |
            'This PR is stale because it has been open 60 days with no activity. Remove stale label or comment or this will be closed in 30 days.'
